app = "chap"
primary_region = "ams"

[[services]]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    port = 443       # expose externally on HTTPS port
    handlers = []    # raw TCP, no Fly TLS proxying

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
