# fly.toml file for chap-proxy
# Docs: https://fly.io/docs/reference/configuration/

app = "chap-proxy"
primary_region = "ams"

[build]

[[services]]
  internal_port = 3128
  protocol = "tcp"

  [[services.ports]]
    port = 3128
    handlers = []   # no HTTP/HTTPS handling, expose raw TCP

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
