app = "chap"
primary_region = "ams"

[[services]]
  internal_port = 3128
  protocol = "tcp"

  # Existing mapping: still expose Squid on port 443
  [[services.ports]]
    port = 443
    handlers = []

  # New mapping: also expose Squid on port 8080
  [[services.ports]]
    port = 8080
    handlers = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
